name: Pedantic check

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run:  sudo apt-get install -y libnet1-dev libpcap-dev automake autoconf check tcpdump openssh-server
      - name: Pedantic check
        run: ./extra/pedantic.sh
      - name: Install optional dependencies
        run:  sudo apt-get install -y libcap-dev libseccomp-dev
      - name: Pedantic check with optional dependencies
        run: ./extra/pedantic.sh
